kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nacos-mysql-slave-pvc
  namespace: nacos
  labels:
    name: mysql-slave
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi