apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  namespace: nacos
  labels:
    name: mysql-master
spec:
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
        - name: nacos-mysql-master
          image: nacos/nacos-mysql-master:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: nacos-mysql-master-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "nacos_devtest"
            - name: MYSQL_USER
              value: "nacos"
            - name: MYSQL_PASSWORD
              value: "nacos"
            - name: MYSQL_REPLICATION_USER
              value: 'nacos_ru'
            - name: MYSQL_REPLICATION_PASSWORD
              value: 'nacos_ru'
      volumes:
        - name: nacos-mysql-master-data
          persistentVolumeClaim:
            claimName: nacos-mysql-master-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: nacos
  labels:
    name: mysql-master
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-master